spring.application.name=BJTester

spring.jpa.show-sql=true

spring.datasource.url=jdbc:h2:file:./data/mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.batch.jdbc.initialize-schema=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.batch.job.enabled=true